name: Helm Index

on:
  push:
    branches: 
      - main
    paths:
      - '**.tgz'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Helm
        uses: azure/setup-helm@v1.1
        with:
          version: v3.12.0
      - name: Update Index
        run: helm repo index --url https://{{ github.repository_owner }}.github.io/{{ github.event.repository.name }}/ .
      - name: push
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'main'
          commit-message: 'auto: helm repo index'
          force-add: 'true'
          files: index.yaml
